; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Gymnopedie
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env2,@env3,@env1,@env0 ; 00 : Instrument 1
	.word @env5,@env3,@env1,@env0 ; 01 : begeleiding

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $00,$ca,$7f,$00,$02
@env3:
	.byte $c0,$7f,$00,$01
@env4:
	.byte $7f,$00,$00
@env5:
	.byte $00,$ca,$0a,$c9,$09,$c8,$09,$c7,$09,$c6,$0b,$c5,$07,$c4,$09,$c3,$13,$c2,$00,$11

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $cf, $80
@song0ref7:
	.byte $13, $ff, $9d, $48, $00, $cd, $0e, $ff, $9d, $48, $00, $cd
	.byte $41, $0a
	.word @song0ref7
@song0ref22:
	.byte $1f, $cd, $22, $cd, $48, $20, $cd, $1f, $cd, $1a, $cd, $48, $18, $cd, $1a, $cd, $1b, $cd, $48, $16
@song0ref42:
	.byte $ff, $ed, $48, $82, $13, $ff, $ed, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $00, $cd, $80
	.byte $41, $13
	.word @song0ref22
	.byte $48, $1a, $ff, $ed, $48, $1f
	.byte $41, $09
	.word @song0ref42
	.byte $48, $80, $16, $cd, $18, $cd, $19
@song0ref81:
	.byte $cd, $48, $1d, $cd, $1b, $cd, $18, $cd, $48, $1b, $cd, $19, $cd, $18, $cd, $48, $1b, $ff, $ed, $48, $cf, $00, $cd, $1b
	.byte $cd, $48, $1d, $cd, $1e, $cd, $20, $cd, $48, $22, $cd, $19, $cd, $1b
	.byte $41, $08
	.word @song0ref81
	.byte $ff, $ed, $48, $ff, $8b, $00, $91, $1b, $cd, $48, $20, $ff, $ed, $48, $1f, $ff, $ed, $48, $18, $cd, $16, $cd, $18, $cd
	.byte $48, $1a, $cd, $1b, $cd, $1d, $cd, $48, $1a, $cd, $1b, $cd, $1d, $cd, $48, $13, $cd, $0f, $cd, $14, $cd, $48, $19, $ff
	.byte $ed, $48, $1f, $ff, $e9, $00, $81, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $00, $cd, $80
@song0ref184:
	.byte $0c, $ff, $9d, $00, $cd, $13, $ff, $9d, $00, $cd
	.byte $41, $0a
	.word @song0ref184
	.byte $41, $0a
	.word @song0ref184
	.byte $41, $0a
	.word @song0ref184
@song0ref203:
	.byte $0c
@song0ref204:
	.byte $ff, $9d, $00, $cd, $16, $ff, $9d, $00, $cd
	.byte $41, $0a
	.word @song0ref203
	.byte $41, $0a
	.word @song0ref184
	.byte $41, $0a
	.word @song0ref184
	.byte $13
@song0ref223:
	.byte $ff, $9d, $00, $cd, $0f, $ff, $9d, $00, $cd, $11, $ff, $9d, $00, $cd, $18
	.byte $41, $09
	.word @song0ref204
	.byte $1d, $ff, $9d, $00, $cd, $18, $ff, $9d, $00, $cd, $1d
	.byte $41, $09
	.word @song0ref204
	.byte $0f, $ff, $9d, $00, $cd, $19, $ff, $9d, $00, $cd, $22
	.byte $41, $09
	.word @song0ref223
	.byte $16
	.byte $41, $09
	.word @song0ref204
	.byte $14, $ff, $9d, $00, $cd, $1a
	.byte $41, $0e
	.word @song0ref223
	.byte $16, $ff, $9d, $00, $cd, $0a, $cd, $0c, $cd, $16, $ff, $ed, $1b, $ff, $e9, $00, $81, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref304:
	.byte $20, $cd, $27, $ff, $9d, $1b, $cd, $22, $ff, $9d
	.byte $41, $0a
	.word @song0ref304
	.byte $41, $0a
	.word @song0ref304
	.byte $41, $0a
	.word @song0ref304
@song0ref323:
	.byte $20, $cd, $27, $ff, $9d, $1b, $cd, $26, $ff, $9d
	.byte $41, $0a
	.word @song0ref323
	.byte $41, $0a
	.word @song0ref304
	.byte $41, $0a
	.word @song0ref304
	.byte $20, $cd, $27, $ff, $9d, $18, $cd, $1f, $ff, $9d, $1d, $cd, $24, $ff, $9d, $1d, $cd, $1b, $ff, $9d, $1b, $cd, $1b, $ff
	.byte $9d, $16, $cd, $22
@song0ref370:
	.byte $ff, $9d, $1b, $cd, $20, $ff, $9d, $1b, $cd, $20, $ff, $9d, $1b, $cd, $25, $ff, $9d, $1b, $cd, $25, $ff, $9d, $1b, $cd
	.byte $22, $ff, $9d, $1b, $cd, $29
	.byte $41, $09
	.word @song0ref370
	.byte $19, $ff, $9d, $1b, $cd, $2b, $ff, $9d, $1d, $cd, $24, $ff, $9d, $13, $cd, $22, $ff, $9d, $0c, $cd, $1f, $ff, $9d, $11
	.byte $cd, $1a, $ff, $9d, $11, $cd, $1f, $ff, $9d, $11, $cd, $18, $cd, $1d, $cd, $20, $ff, $ed, $22, $ff, $e9, $00, $81, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref455:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $41, $08
	.word @song0ref455
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $42
	.word @song0ch3loop
