; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_splash

@sfx_ntsc_splash:
	.byte $8a,$04,$89,$3f,$06,$89,$38,$06,$89,$34,$06,$8a,$03,$89,$36,$06
	.byte $89,$32,$06,$00

.export sounds
