; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_bird
	.word @sfx_ntsc_splash

@sfx_ntsc_bird:
	.byte $81,$2e,$82,$00,$80,$3f,$89,$f0,$01,$81,$2d,$01,$81,$2c,$01,$81
	.byte $2b,$01,$81,$2a,$01,$81,$29,$01,$81,$28,$80,$3e,$01,$81,$27,$80
	.byte $3d,$01,$81,$26,$80,$3c,$01,$81,$25,$80,$3b,$01,$81,$24,$80,$3a
	.byte $01,$81,$23,$80,$39,$01,$81,$22,$80,$38,$01,$81,$21,$01,$81,$20
	.byte $80,$37,$01,$81,$1f,$80,$36,$01,$81,$1e,$80,$35,$01,$81,$1d,$80
	.byte $34,$01,$81,$1c,$80,$33,$01,$81,$1b,$80,$32,$01,$81,$1a,$80,$31
	.byte $01,$81,$19,$01,$81,$18,$00
@sfx_ntsc_splash:
	.byte $8a,$04,$89,$3f,$06,$89,$38,$06,$89,$34,$06,$8a,$03,$89,$36,$06
	.byte $89,$32,$06,$00

.export sounds
